name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Check out Prodigy
        uses: actions/checkout@v4
        with:
          repository: explosion/prodigy
          ref: v1.14.11
          path: ./prodigy
          ssh-key: ${{ secrets.GHA_PRODIGY_READ }}

      - name: Install prodigy
        run: |
          ls -la
          pip install ./prodigy
          python -m prodigy --help

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install ruff pytest
      
      - name: Run ruff
        if: always()
        shell: bash
        run: python -m ruff prodigy_segment/__init__.py tests

      - name: Run pytest
        if: always()
        shell: bash
        run: python -m pytest tests
